### ISSUE TITLE
Nothing displayed

### ISSUE THREAD

**Issue by leader80** [camptocamp/puppet-mapserver#11]
Hi,

I managed to start the docker image but when I connect to the apache I get following error:

"No query information to decode. QUERY_STRING is set, but empty."

Any idea how to fix this?

Thanks
G.

**Comment by sbrunner** [comment]
You all ready use a WMS server?

One request you can do is: ...?SERVICE=WMS&REQUEST=GetCapabilitiesVERSION=1.1.1

And it should return an XML that describe what can the server do...

**Comment by leader80** [comment]
Hi,

thanks for the reply, I scare there is no map loaded:

 msLoadMap(): Unable to access file. (/etc/mapserver/mapserver.map) 

How do I set the map to be loaded?

Thanks
G.

**Comment by pvalsecc** [comment]
I guess you are talking about this repo: https://github.com/camptocamp/docker-mapserver
You don't seem to use the puppet module, here.

This Docker image doesn't work without adding file to it: `/etc/mapserver/mapserver.map`

Maybe you want to consult the mapserver documentation as well: http://mapserver.org/introduction.html#mapserver-overview

This service is not to be used standalone as you seem to think. You need a WMS of WFS client and a lot of tricky configuration.

**Comment by leader80** [comment]
fully right, thanks for the info!
